service: asagi

provider:
  name: aws
  runtime: go1.x

  apiKeys:
    - ${env:MY_API_KEY}
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

  stage: dev
  region: ap-northeast-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  echo:
    handler: bin/echo
    events:
      - http:
          path: asagi/echo
          method: get
      - http:
          path: asagi/echo
          method: post
          private: true
